```{r, echo=FALSE}
source('report/report-fun.R')
options(width =160)

# Load all data
dat <- loadStudies(reprocess=FALSE)

spLevelInfo  <-  function(data){
  spec         <-  data.frame(species=as.character(unique(data$species)), stringsAsFactors=FALSE)
  for(z in c("family", "pft")){
    spec[[z]]  <-  as.character(data[[z]][match(spec$species,data$species)])
    i          <-  spec[[z]]=="" | is.na(spec[[z]]) 
    if(any(i)){
      spec[[z]][i]  <-  "????"
    }
  }
  j            <-  spec$species=="" | is.na(spec$species) 
  if(any(j)){
    spec$species[j]  <-  "????"
  }
  spec
}

```


## Study details

### Location

**Global map**

```{r echo=FALSE, fig.width=8, fig.height=6, message=FALSE, warning=FALSE}
prepdata  <-  prepMapInfo(dat$data)
drawWorldPlot (prepdata)
```


### Species data

```{r echo=FALSE, message=FALSE, warning=FALSE, comment=''}
(spLevelInfo(dat$data))

```

## Plots of data

This is how the study `r .study` (each color represents a species) fits in the entire dataset (grey).

```{r fig.height=8, fig.width=8, echo=FALSE, warning=FALSE, message=FALSE}
bivarPlot(dat$data, "h.t", "a.lf")

tmp <- bivarPlotColorBy(dat$data, "a.lf", "h.t",colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)


tmp <- bivarPlotColorBy(dat$data, "m.ss", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)


tmp<-bivarPlotColorBy(dat$data, "h.t", "a.lf", colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
bivarPlot.Legend(tmp)
tmp <- bivarPlotColorBy(dat$data, "m.t", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
tmp <- bivarPlotColorBy(dat$data, "m.to", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
source('report/report-fun.R')
tmp <- bivarPlotColorBy(dat$data, "m.st", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
tmp <- bivarPlotColorBy(dat$data, "m.ss", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
tmp <- bivarPlotColorBy(dat$data, "m.lf", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
tmp <- bivarPlotColorBy(dat$data, "m.rt", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
tmp <- bivarPlotColorBy(dat$data, "m.sh", "h.t",  colorBy = dat$data$vegetation)
bivarPlot.Legend(tmp)
tmp <- bivarPlotColorBy(dat$data, "a.st", "a.lf",  colorBy = dat$data$vegetation)
tmp <- bivarPlotColorBy(dat$data, "a.ssba", "a.lf",  colorBy = dat$data$vegetation)
tmp <- bivarPlotColorBy(dat$data, "a.stba", "a.lf",  colorBy = dat$data$vegetation)
tmp <- bivarPlotColorBy(dat$data, "a.stbh", "a.lf",  colorBy = dat$data$vegetation)
tmp <- bivarPlotColorBy(dat$data, "m.st", "m.lf",  colorBy = dat$data$vegetation)


```


  
  
  