% How to build a plant
% Daniel Falster; Remko Duursma; Diego Barneche

Goal: Establish foundations for modelling plant growth through ontogeny, emphasising simple hypotheses, areas where important differences lie (e.g. between species, between vegetation, light env)

# Relationships to test

## An allometric relation between total leaf area and plant height

- is there linear log-log relationship between leaf area and height across size range?
- slope seems to increase in the upper range of heights, leaf area and (less distinctly) leaf mass increase more steeply relative to height gain. Or to put that the other way round, height gain slows even though canopy expansion is continuing
  - how much of this is higher SLA in the taller plants?
  - how much of it is a between species rather than a within-species effect?
  - it should be apparent also in the relation between stem or sapwood cross

- how much variation between species within sites; species across sites; vegetation types; light env within sites?

## The pipe model, relating cross-sectional area of sapwood and bark to total leaf area.

- is there linear log-log relationship across size range between sapwood cross section and total leaf area?
  - for smaller stems: use total area

- expect slope different to 1 for total stem cross section, because incorporates heartwood
  - better with stem area at crown base (as per Makela hypothesis)

- is there linear log-log relationship across size range between bark cross section and total leaf area?
  - for smaller stems: use total area

- how much variation between species within sites; species across sites; vegetation types; light env within sites?

## Ratio of root mass to leaf area.

- is there linear log-log relationship across size range between root mass and total leaf area?

- how much variation between species within sites; species across sites; vegetation types; light env within sites?

## Crown width and surface area

- is there linear log-log relationship across size range between root mass and total leaf area?

## Leaf mass fraction


## Equations for total biomass

- stem biomass predicted from height & traits via simple equation:
- leaf biomass?

