Report for study: `r .study`
========================================================

Study reference: `r .dat$ref`

Study contact: `r .dat$contact$name`.

Contact email: `r .dat$contact$email`.

Contact address: `r .dat$contact$address`.


Data description
-----------------------------------

Data for `r length(.dat$data$dataset)` individuals from `r length(unique(.dat$data$location))` locations covering `r length(unique(.dat$data$species))` species.

The dataset includes `r length(unique(.dat$data$species))` species belonging to `r length(unique(.dat$data$family))` family(ies), presenting `r length(unique(.dat$data$pft))` functional type(s), growing in `r length(unique(.dat$data$growingCondition))` condition(s) within `r length(unique(.dat$data$vegetation))` major type(s) of habitat:


Number of records for each variable
-----------------------------------

```{r echo=FALSE, comment=''}
counts  <-  apply(!is.na(.dat$data), MARGIN=2, FUN = sum)
counts  <-  counts[counts>0]  #only include no zeros
counts  <-  counts[names(counts)%in%var.def$Variable[var.def$Group=="tree"]]
cbind(counts)
```


More details
------------------------------------

### Please check if the points on the map match locations and coordinates  

```{r echo=FALSE, fig.width=8, fig.height=6, message=FALSE, warning=FALSE}
prepdata  <-  prepMapInfo(alldata$data, study)
drawWorldPlot (prepdata)
```



### Please analyse if points on country map match locations and coordinates  

```{r echo=FALSE, fig.width=8, fig.height=6, message=FALSE, warning=FALSE}
repMissingInfo(prepdata)
drawCountryPlot(prepdata)
```



### Location level - please provide any missing information
```{r echo=FALSE, message=FALSE, warning=FALSE, comment=''}
locLevelInfo(.dat$data)
```

### Stand level - please provide any missing information
```{r echo=FALSE, message=FALSE, warning=FALSE, comment=''}
standLevelInfo(.dat$data)
```

### Species level - please provide any missing information
```{r echo=FALSE, message=FALSE, warning=FALSE, comment=''}
spLevelInfo(.dat$data)
```

### Method - please provide any missing information/follow template
```{r echo=FALSE, message=FALSE, warning=FALSE, comment=''}
printMeta(.dat$data)
```

Plot of data
---------------------------------

This is how the study `r .study` (red symbols) fits in the entire dataset.

```{r fig.height=8, fig.width=8, echo=FALSE, warning=FALSE, message=FALSE}
makePlotPanel(d$data, .study, pdf=FALSE, quiet=TRUE)
```


  
  
  